name: neurodatapub-env

channels:
- conda-forge
- defaults
- anaconda

dependencies:
- python=3.8.10
- pip=21.1.3
- traits=6.2.0
- traitsui=7.2.1
- datalad=0.14.5
- rsync=3.2.3
# - git-annex=8.20210621

- pip:
    - argparse==1.4.0
    - datalad-neuroimaging==0.3.1
    - jsonschema==3.2.0
    - pybids==0.13.1
    - nbsphinx==0.8.6
    - sphinx-argparse==0.2.5
    - sphinxcontrib-apidoc==0.3.0
    - sphinxcontrib-napoleon==0.7
    - sphinx-rtd-theme==0.5.2
