name: neurodatapub-env

channels:
- conda-forge
- defaults
- anaconda

dependencies:
- python=3.8.10
- pip=21.1.3
- traits=6.2.0
- traitsui=7.2.1
- datalad=0.14.5

- pip:
    - datalad-neuroimaging==0.3.1
